### ISSUE TITLE
is this project maintained?

### ISSUE THREAD

**Issue by bpmooch** [starnutoditopo/react-typescript-flight-indicators#4]
see title

**Comment by starnutoditopo** [comment]
This is a hobby project. My will is to maintain it, but, unfortunately, I haven't got much time.
I started to look at your pull requests, but I haven't finished, yet.
As you are interested in the project, i can give you grants to carry it on: I'd be very happy if you' like to!

**Comment by bpmooch** [comment]
yea, that would be great. happy to do it

**Comment by starnutoditopo** [comment]
> yea, that would be great. happy to do it

I added you as collaborator.

Thanks!
